---
title: "HESA analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw())
knitr::opts_chunk$set(
  echo = FALSE,
  results = FALSE,
  message = FALSE, 
  include = TRUE,
  warning = FALSE,
  fig.width = 3, fig.height = 2
)
```

```{r read in in data}

# Read in data for table 1 on the following website
# https://www.hesa.ac.uk/data-and-analysis/finances/income

df <- read_csv("https://www.hesa.ac.uk/data-and-analysis/finances/table-1.csv", skip = 12)

```

```{r summarise data}

# The following code 

# The categories below are those which HESA uses to on Table 1
# https://www.hesa.ac.uk/data-and-analysis/finances/income
# To generate income and expenditure

df %>% 
  mutate(income_outgoing = case_when(
    Category == "Tuition fees and education contracts" ~ "inc",
    Category == "Funding body grants" ~ "inc",
    Category == "Research grants and contracts" ~ "inc",
    Category == "Other income" ~ "inc",
    Category == "Investment income" ~ "inc",
    Category == "Donations and endowments" ~ "inc",
    Category == "Staff costs" ~ "out",
    Category == "Restructuring costs" ~ "out",
    Category == "Other operating expenses" ~ "out",
    Category == "Depreciation and amortisation" ~ "out",
    Category == "Interest and other finance costs" ~ "out",
    TRUE ~ "no_category")) %>% 
  mutate(year_ending = case_when(
    `Academic year` == "2015/16" ~ 2016,
    `Academic year` == "2016/17" ~ 2017,
    `Academic year` == "2017/18" ~ 2018,
    `Academic year` == "2018/19" ~ 2019,
    `Academic year` == "2019/20" ~ 2020,
    `Academic year` == "2020/21" ~ 2021,
    TRUE ~ 0)) %>% 
  filter(income_outgoing != "no_category") %>% # removes categories not contributing to overall income / expenditure
  filter(`HE Provider` != "Year to date total",
         `HE Provider` != "Total") %>% # remove nuisance variables from HESA data
  mutate(value = 1000*as.numeric(`Value(£000s)`)) %>% # Convert 1000s into raw numbers
  group_by(`HE Provider`, Category, income_outgoing, year_ending) %>% 
  summarise(value = mean(value)) -> # This is necessary because observations are duplicated for each HE Provider by Category by year_ending combination. The columns responsible for this are columns 3 and 4 (Country of HE Provider / Region of HE Provider)
  df

```

```{r plot proportion outgoings by category}

df %>%
    filter(income_outgoing == "out") %>%
    group_by(year_ending) %>% 
    summarise(total_outgoings_by_year_UK = sum(value, na.rm = TRUE)) %>% 
    left_join(df, by = c("year_ending")) %>% 
    filter(income_outgoing == "out") %>% 
    group_by(Category, year_ending, total_outgoings_by_year_UK) %>% 
    summarise(total_outgoings_by_year_and_category_UK = sum(value, na.rm = TRUE)) %>% 
    mutate(perc = (total_outgoings_by_year_and_category_UK/
                  total_outgoings_by_year_UK) *100) -> df.outgoings.perc



g <- ggplot(data = df.outgoings.perc %>% filter(year_ending != 2021) %>% filter(Category == "Staff costs"),
       aes(x = year_ending, y = perc, fill = Category))

g <- g + geom_line()
g <- g + scale_y_continuous(breaks = seq(0, 100, by = 10))
g <- g + xlab("Year ending")
g <- g + ylab("Percentage of expenditure on staff costs")
g <- g + ylim(40, 70)


g <- g + geom_hline(yintercept = c(50,60),
                    colour = "dark blue",
                    linetype = "dashed")

g <- g + ggtitle("Percentage of expenditure on staff costs")

g

```


```{r plot proportion income spent on staff}

df %>%
    filter(income_outgoing == "inc") %>%
    group_by(year_ending) %>% 
    summarise(total_income_by_year_UK = sum(value, na.rm = TRUE)) %>%
    left_join(df, by = c("year_ending")) %>%
    filter(Category == "Staff costs") %>%
    group_by(year_ending, total_income_by_year_UK) %>%
    summarise(total_staff_costs_by_year = sum(value, na.rm = TRUE)) %>% 
    mutate(perc = (total_staff_costs_by_year/
                  total_income_by_year_UK) *100) -> df.propn.inc.staff


g <- ggplot(data = df.propn.inc.staff %>% filter(year_ending != 2021 & year_ending != 2019),
       aes(x = year_ending, y = perc))

g <- g + geom_line()
g <- g + scale_y_continuous(breaks = seq(0, 100, by = 10))
g <- g + xlab("Year ending")
g <- g + ylab("Percentage of income spent on staff")

g <- g + geom_hline(yintercept = c(40,50,60),
                    colour = "dark blue",
                    linetype = "dashed")

g <- g + ggtitle("Percentage of income spent on staff")

g

```




